updates

diff --git a/lib/create-cluster b/lib/create-cluster
--- a/lib/create-cluster
+++ b/lib/create-cluster
@@ -1,13 +1,14 @@
 #!/bin/bash
 
+RETRY_INT=10
+
 function main() {
   cd $(dirname $0)
   [ -f settings ] && . settings || { err "file settings not found"; return 2; }
   local fatal=0
-  [[ $CLOUD_PROVIDER ]] || { err "Missing setting CLOUD_PROVIDER"; fatal=1; }
-  [[ $CLUSTER_NAME ]] || { err "Missing setting CLUSTER_NAME"; fatal=1; }
-  [[ $DNS_DOMAIN ]] || { err "Missing setting DNS_DOMAIN"; fatal=1; }
-  [ $fatal -eq 1 ] && return 2
+  ./check-system || { fatal=1; }
+  ./check-config || { fatal=1; }
+  [ $fatal -eq 1 ] && { err "Unable to continue. See above."; return 2; }
 
   SSHKEY=${HOME}/.ssh/aporeto_lab
   FQDN=${CLUSTER_NAME}.${DNS_DOMAIN}
@@ -53,10 +54,19 @@ _aws() {
   [[ $AWS_KUBE_CNI ]] && kops+=" --networking=$AWS_KUBE_CNI"
   kops+=" --yes"
   export KUBECONFIG=$PWD/kube.config
-  set -x
   aws s3 mb $bucket || return $?
   $kops || return $?
   kops export kubecfg $FQDN --state=${bucket}/state || return $?
+  err "Applying DNS fix, this may take a few minutes"
+  while [ true ]; do
+    ./update-aws-dns && break || {
+      err "Unable to update AWS DNS; will try again in $RETRY_INT"
+      sleep $RETRY_INT
+    }
+  done
+  err "DNS Updated"
+
+  err "Completed successfully"
 }
 
 err() { echo "$@" 1>&2; }
diff --git a/lib/setup-aporeto b/lib/setup-aporeto
--- a/lib/setup-aporeto
+++ b/lib/setup-aporeto
@@ -6,12 +6,9 @@ function main() {
   cd $(dirname $0)
   [ -f settings ] && . settings || { err "file settings not found"; return 2; }
   local fatal=0
-  [[ $CLOUD_PROVIDER ]] || { err "Missing setting CLOUD_PROVIDER"; fatal=1; }
-  [[ $CLUSTER_NAME ]] || { err "Missing setting CLUSTER_NAME"; fatal=1; }
-  [[ $DNS_DOMAIN ]] || { err "Missing setting DNS_DOMAIN"; fatal=1; }
-  [[ $PARENT_NAMESPACE ]] || { err "Missing setting PARENT_NAMESPACE"; fatal=1; }
-  [[ $APOCTL_API ]] || { err "Missing setting APOCTL_API"; fatal=1; }
-  [ $fatal -eq 1 ] && return 2
+  ./check-system || { fatal=1; }
+  ./check-config || { fatal=1; }
+  [ $fatal -eq 1 ] && { err "Unable to continue. See above."; return 2; }
 
   FQDN=${CLUSTER_NAME}.${DNS_DOMAIN}
   local bucket="s3://k8s.${FQDN}"
@@ -37,7 +34,7 @@ function _aws() {
   _aws_auth_nodes > $CONFIG/aws_auth_nodes.json
   _cert > $CONFIG/cert.yaml
 
-  cat policy/aporeto-policy.yaml | sed "s/:::CLUSTER_NAME:::/$CLUSTER_NAME/g" > $CONFIG/aporeto-policy.yaml
+  cat config/aporeto-policy.yaml | sed "s/:::CLUSTER_NAME:::/$CLUSTER_NAME/g" > $CONFIG/aporeto-policy.yaml
 
   openssl ecparam -name prime256v1 -genkey -noout -out ${CONFIG}/key.pem
   openssl req -new -key ${CONFIG}/key.pem -subj "/CN=system:serviceaccount:aporeto:enforcerd" -out ${CONFIG}/key.csr
diff --git a/lib/update-aws-dns b/lib/update-aws-dns
--- a/lib/update-aws-dns
+++ b/lib/update-aws-dns
@@ -1,50 +1,52 @@
-#!/bin/bash -e
+#!/bin/bash
 
 function main() {
   cd $(dirname $0)
   [ -f settings ] && . settings || { err "file settings not found"; return 2; }
   local fatal=0
-  [[ $CLOUD_PROVIDER ]] || { err "Missing setting CLOUD_PROVIDER"; fatal=1; }
-  [[ $CLUSTER_NAME ]] || { err "Missing setting CLUSTER_NAME"; fatal=1; }
-  [[ $DNS_DOMAIN ]] || { err "Missing setting DNS_DOMAIN"; fatal=1; }
-  [[ $AWS_KUBE_REGION ]] || { err "Missing setting AWS_KUBE_REGION"; fatal=1; }
-  [[ $AWS_KUBE_ZONE ]] || { err "Missing setting AWS_KUBE_ZONE"; fatal=1; }
-  [[ $AWS_DOMAIN_ID ]] || { err "Missing setting AWS_DOMAIN_ID"; fatal=1; }
-  [ $fatal -eq 1 ] && return 2
+  ./check-system || { fatal=1; }
+  ./check-config || { fatal=1; }
+  [ $fatal -eq 1 ] && { err "Unable to continue. See above."; return 2; }
 
   [[ "$CLOUD_PROVIDER" == "AWS" ]] || { err "Cloud provider must be AWS"; return 2; }
 
-  FQDN=${CLUSTER_NAME}.${DNS_DOMAIN}
+  local fqdn=${CLUSTER_NAME}.${DNS_DOMAIN}
 
-  trap _cleanup EXIT
-  TMP=$(mktemp)
-  _setip
-  _update
+  err "Attempting to get IP from AWS API"
+  local ip=$(_getip)
+  [[ $ip ]] || { err "IP not found"; return 3; }
+  err "Retrieved ip $ip"
+
+  err "Attempting to update record A record api.$fqdn with IP $ip"
+  _setip $fqdn $ip || { err "Failed to update record"; return 4; }
   err "Completed successfully"
 }
 
-function _cleanup {
-  [[ $TMP ]] && rm -rf $TMP;
+_getip() {
+  local values=master-${AWS_KUBE_REGION}${AWS_KUBE_ZONE}.masters.${CLUSTER_NAME}.${DNS_DOMAIN}
+  echo $(
+    aws ec2 --region $AWS_KUBE_REGION describe-instances --filters Name=tag:Name,Values=$values \
+    --query "Reservations[*].Instances[*].PublicIpAddress" --output=text
+  )
 }
 
-_setip()
-{
-local values=master-${AWS_KUBE_REGION}${AWS_KUBE_ZONE}.masters.${CLUSTER_NAME}.${DNS_DOMAIN}
-while [ true ]; do
-  ip=$(aws ec2 --region $AWS_KUBE_REGION describe-instances --filters Name=tag:Name,Values=$values --query "Reservations[*].Instances[*].PublicIpAddress" --output=text)
-  [[ $ip ]] && break
-  { err "IP not found; will try again in 5 seconds"; }
-  sleep 5
-done
+_setip() {
+    aws route53 change-resource-record-sets --hosted-zone-id $AWS_DOMAIN_ID \
+    --change-batch "$(_json_a_record $fqdn $ip)"
+}
 
-cat <<EOF > $TMP
+_json_a_record()
+{
+local fqdn=$1
+local ip=$2
+cat <<EOF
 {
   "Comment": "Update A Record",
   "Changes": [
     {
       "Action": "UPSERT",
       "ResourceRecordSet": {
-        "Name": "api.$FQDN",
+        "Name": "api.$fqdn",
         "Type": "A",
         "TTL": 10,
         "ResourceRecords": [
@@ -57,15 +59,6 @@ cat <<EOF > $TMP
   ]
 }
 EOF
-}
-
-_update() {
-  while [ true ]; do
-    err "Updating A record api.$FQDN with IP $ip"
-    aws route53 change-resource-record-sets --hosted-zone-id $AWS_DOMAIN_ID --change-batch file://$TMP && { err "record updated"; return 0; }
-    err "Updated failed; will try again in 5 seconds"
-    sleep 5
-  done
 }
 
 err() { echo "$@" 1>&2; }
